trigger:
- main

pool:
  name: 'testing_pool'

steps:
- checkout: self

- script: |
    python --version
    python -m pip --version
  displayName: 'Verify Local Python'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade Pip'

- script: |
    python -m pip install pytest pytest-azurepipelines
  displayName: 'Install Test Tools'
